spring:
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
cloud:
  aws:
    credentials:
      access-key: ${aws.credentials.accessKey}
      secret-key: ${aws.credentials.secretKey}
      send-mail-to: dgswcns@gmail.com
    region: ap-northeast-2