spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ida}
    username: ${DB_USERNAME:cns}
    password: ${DB_PASSWORD:cns}
    driver-class-name: com.mysql.cj.jdbc.Driver


    hikari:
      maximum-pool-size: 4
      pool-name: HIKARI_CONNECTION_POOL

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
